name: Alerta

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v4

      - name: Ejecutar Hola Mundo
        run: node hola.js

      - name: Enviar notificacion a ntfy
        run: |
          curl -d "Notificacion de Martin Gomez: push a main en ${{ github.repository }}" https://ntfy.sh/devops-itla
